[versions]
agp = "9.4.0"
kotlin = "2.4.20"
coroutines = "1.10.2"
composeBom = "2026.05.00"
activity = "1.13.0"
lifecycle = "2.10.0"
junit = "4.13.2"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
