const REGISTRY_URL='../../../blueprint/vessel-studio-practicum-registry.json';
const REGISTRATION_URL='../../../blueprint/vessel-studio-practicum/registration.json';
const clone=(value)=>structuredClone(value);
const byId=(id)=>document.getElementById(id);
const exactKeys=(value,keys)=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&keys.every((key)=>Object.hasOwn(value,key));
const [registry,registration]=await Promise.all([
  fetch(REGISTRY_URL,{cache:'no-store'}).then((response)=>{if(!response.ok)throw new Error('Vessel Studio registry unavailable');return response.json()}),
  fetch(REGISTRATION_URL,{cache:'no-store'}).then((response)=>{if(!response.ok)throw new Error('Vessel Studio registration unavailable');return response.json()})
]);
const strings=registration.strings;
let locale='en';
const emptySelections=()=>({avatarRef:null,colorRef:null,glowRef:null,voiceProfileRef:null,namePresentation:null,environmentRef:null});
let state={revision:0,sessionGeneration:1,selections:emptySelections(),previewAvatarRef:null,previewVoiceRef:null,offerStatus:'DRAFT',events:[],history:[]};
const catalogs={
 avatarRef:new Map(registry.options.avatars.map((item)=>[item.optionRef,item])),
 colorRef:new Map(registry.options.colors.map((item)=>[item.optionRef,item])),
 glowRef:new Map(registry.options.glows.map((item)=>[item.optionRef,item])),
 voiceProfileRef:new Map(registry.options.voices.map((item)=>[item.optionRef,item])),
 environmentRef:new Map(registry.options.environments.map((item)=>[item.optionRef,item]))
};
function t(ref){return strings[locale]?.[ref]??strings.en?.[ref]??ref}
function labelFor(ref){if(!ref)return t('vessel-studio.empty');for(const map of Object.values(catalogs)){const item=map.get(ref);if(item)return t(item.labelStringRef)}return ref}
function populate(id,items){const select=byId(id),previous=select.value;select.replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=t('vessel-studio.choose');select.append(placeholder);for(const item of items){const option=document.createElement('option');option.value=item.optionRef;option.textContent=t(item.labelStringRef);select.append(option)}select.value=[...select.options].some((option)=>option.value===previous)?previous:''}
function applyStrings(){document.documentElement.lang=locale;for(const node of document.querySelectorAll('[data-i18n]'))node.textContent=t(node.dataset.i18n);for(const node of document.querySelectorAll('[data-i18n-placeholder]'))node.placeholder=t(node.dataset.i18nPlaceholder);populate('avatarOption',registry.options.avatars);populate('colorOption',registry.options.colors);populate('glowOption',registry.options.glows);populate('voiceOption',registry.options.voices);populate('environmentOption',registry.options.environments);render()}
function validRef(field,value){return typeof value==='string'&&catalogs[field]?.has(value)}
function validateEvent(eventType,payload){const expected=registry.eventPayloadKeys[eventType];if(!expected||!exactKeys(payload,expected))return false;if(eventType.startsWith('AVATAR_'))return validRef('avatarRef',payload.avatarRef);if(eventType==='COLOR_CHANGED')return validRef('colorRef',payload.colorRef)&&validRef('glowRef',payload.glowRef);if(eventType.startsWith('VOICE_'))return validRef('voiceProfileRef',payload.voiceProfileRef);if(eventType==='NAME_PRESENTATION_SELECTED')return typeof payload.namePresentation==='string'&&payload.namePresentation.trim().length>0&&payload.namePresentation.trim().length<=40;if(eventType==='ENVIRONMENT_SELECTED')return validRef('environmentRef',payload.environmentRef);return eventType==='OPTION_REVERTED'||eventType==='VESSEL_OFFER_FINALIZED_REFERENCE_ONLY'}
function completeOffer(){const s=state.selections;return Boolean(s.avatarRef&&s.colorRef&&s.glowRef&&s.voiceProfileRef&&s.namePresentation&&s.environmentRef)}
function selectionSnapshot(){return clone({selections:state.selections,offerStatus:state.offerStatus})}
function applyMutation(eventType,payload){if(['AVATAR_OPTION_SELECTED','COLOR_CHANGED','VOICE_SELECTED','NAME_PRESENTATION_SELECTED','ENVIRONMENT_SELECTED'].includes(eventType))state.history.push(selectionSnapshot());if(eventType==='AVATAR_OPTION_PREVIEWED')state.previewAvatarRef=payload.avatarRef;if(eventType==='AVATAR_OPTION_SELECTED'){state.selections.avatarRef=payload.avatarRef;state.offerStatus='DRAFT'}if(eventType==='COLOR_CHANGED'){state.selections.colorRef=payload.colorRef;state.selections.glowRef=payload.glowRef;state.offerStatus='DRAFT'}if(eventType==='VOICE_PREVIEWED')state.previewVoiceRef=payload.voiceProfileRef;if(eventType==='VOICE_SELECTED'){state.selections.voiceProfileRef=payload.voiceProfileRef;state.offerStatus='DRAFT'}if(eventType==='NAME_PRESENTATION_SELECTED'){state.selections.namePresentation=payload.namePresentation.trim();state.offerStatus='DRAFT'}if(eventType==='ENVIRONMENT_SELECTED'){state.selections.environmentRef=payload.environmentRef;state.offerStatus='DRAFT'}if(eventType==='OPTION_REVERTED'){const previous=state.history.pop();if(!previous)return false;state.selections=clone(previous.selections);state.offerStatus='DRAFT'}if(eventType==='VESSEL_OFFER_FINALIZED_REFERENCE_ONLY'){if(!completeOffer())return false;state.offerStatus='REFERENCE_ONLY_READY'}return true}
function transact({eventType,payload={},expectedRevision}={}){if(expectedRevision!==state.revision)return{disposition:'STALE_REJECTED',revision:state.revision,effects:false};if(!registry.eventTypes.includes(eventType)||!validateEvent(eventType,payload))return{disposition:'INVALID_REJECTED',revision:state.revision,effects:false};const before=clone(state);if(!applyMutation(eventType,payload)){state=before;return{disposition:'INVALID_REJECTED',revision:state.revision,effects:false}}state.revision+=1;const event={eventRef:'event.vessel-studio.practicum.'+String(state.sessionGeneration).padStart(2,'0')+'.'+String(state.revision).padStart(3,'0'),eventType,payload:clone(payload),revision:state.revision};state.events.push(event);render();return{disposition:'APPLIED',previousRevision:expectedRevision,nextRevision:state.revision,eventRef:event.eventRef,effects:false}}
function reset({expectedRevision}={}){if(expectedRevision!==state.revision)return{disposition:'STALE_REJECTED',revision:state.revision,effects:false};const nextGeneration=state.sessionGeneration+1;state={revision:0,sessionGeneration:nextGeneration,selections:emptySelections(),previewAvatarRef:null,previewVoiceRef:null,offerStatus:'DRAFT',events:[],history:[]};byId('namePresentation').value='';for(const id of ['avatarOption','colorOption','glowOption','voiceOption','environmentOption'])byId(id).value='';render();return{disposition:'APPLIED_RESET',nextRevision:0,sessionGeneration:nextGeneration,effects:false}}
function snapshot(){return clone({revision:state.revision,sessionGeneration:state.sessionGeneration,selections:state.selections,previewAvatarRef:state.previewAvatarRef,previewVoiceRef:state.previewVoiceRef,offerStatus:state.offerStatus,eventTrail:state.events,effects:false,referenceOnly:true,persistence:'EPHEMERAL_BROWSER_SESSION',currentWorkStateAuthority:false,MemoryAuthority:false,JournalAuthority:false,modelRuntimeAuthority:false,SDKAuthority:false,save:false,deploy:false,publish:false})}
function setPreview(){const selected=state.selections.avatarRef??state.previewAvatarRef;const avatar=catalogs.avatarRef.get(selected);const color=catalogs.colorRef.get(state.selections.colorRef);const glow=catalogs.glowRef.get(state.selections.glowRef);const root=byId('vesselPreview');root.dataset.shape=avatar?.shapeClass??'NONE';root.dataset.glow=glow?.glowClass??'NONE';root.style.setProperty('--vessel-color',color?.cssValue??'#aab4c0')}
function render(){setPreview();byId('offerStatus').textContent=state.offerStatus==='REFERENCE_ONLY_READY'?t('vessel-studio.offer.ready'):t('vessel-studio.offer.draft');byId('offerAvatar').textContent=labelFor(state.selections.avatarRef);byId('offerColor').textContent=labelFor(state.selections.colorRef);byId('offerGlow').textContent=labelFor(state.selections.glowRef);byId('offerVoice').textContent=labelFor(state.selections.voiceProfileRef);byId('offerName').textContent=state.selections.namePresentation??t('vessel-studio.empty');byId('offerEnvironment').textContent=labelFor(state.selections.environmentRef);byId('revisionBadge').textContent='rev '+state.revision+' · session '+state.sessionGeneration;byId('reviewOffer').disabled=!completeOffer();byId('revert').disabled=state.history.length===0;const list=byId('eventTrail');list.replaceChildren();for(const event of state.events.slice(-10)){const li=document.createElement('li');li.textContent=event.revision+'. '+event.eventType+' · '+JSON.stringify(event.payload);list.append(li)}}
function commit(eventType,payload={}){const receipt=transact({eventType,payload,expectedRevision:state.revision});byId('transactionStatus').textContent=receipt.disposition+' · rev '+(receipt.nextRevision??receipt.revision);return receipt}
byId('language').addEventListener('change',(event)=>{locale=event.target.value;applyStrings()});
byId('avatarPreview').addEventListener('click',()=>{const avatarRef=byId('avatarOption').value;if(avatarRef)commit('AVATAR_OPTION_PREVIEWED',{avatarRef})});
byId('avatarUse').addEventListener('click',()=>{const avatarRef=byId('avatarOption').value;if(avatarRef)commit('AVATAR_OPTION_SELECTED',{avatarRef})});
byId('colorGlowUse').addEventListener('click',()=>{const colorRef=byId('colorOption').value,glowRef=byId('glowOption').value;if(colorRef&&glowRef)commit('COLOR_CHANGED',{colorRef,glowRef})});
byId('voicePreview').addEventListener('click',()=>{const voiceProfileRef=byId('voiceOption').value;if(!voiceProfileRef)return;const receipt=commit('VOICE_PREVIEWED',{voiceProfileRef});if(receipt.disposition==='APPLIED')byId('voicePreviewStatus').textContent=t(catalogs.voiceProfileRef.get(voiceProfileRef).previewStringRef)});
byId('voiceUse').addEventListener('click',()=>{const voiceProfileRef=byId('voiceOption').value;if(voiceProfileRef)commit('VOICE_SELECTED',{voiceProfileRef})});
byId('nameUse').addEventListener('click',()=>{const namePresentation=byId('namePresentation').value;if(namePresentation.trim())commit('NAME_PRESENTATION_SELECTED',{namePresentation})});
byId('environmentUse').addEventListener('click',()=>{const environmentRef=byId('environmentOption').value;if(environmentRef)commit('ENVIRONMENT_SELECTED',{environmentRef})});
byId('revert').addEventListener('click',()=>commit('OPTION_REVERTED',{}));
byId('reviewOffer').addEventListener('click',()=>commit('VESSEL_OFFER_FINALIZED_REFERENCE_ONLY',{}));
byId('reset').addEventListener('click',()=>{const receipt=reset({expectedRevision:state.revision});byId('transactionStatus').textContent=receipt.disposition+' · rev '+(receipt.nextRevision??receipt.revision);byId('voicePreviewStatus').textContent=''});
globalThis.__VEXLIFE_VESSEL_STUDIO__={snapshot,transact,reset,registryRef:registry.registryRef,featureRef:registry.featureRef};
applyStrings();
document.documentElement.dataset.vesselStudioReady='true';
