import{validateRegistry,entryView,compareEntryRebind,project,admission,canAdvance,recover}from'./core.js';
const $=s=>document.querySelector(s),REG='../../../blueprint/relationships-browser-registry.json';let r,t,state={lang:'en',count:0,page:1,entry:null,invitation:'NONE',identity:'UNKNOWN',decision:'DEFER',localClass:'FRIEND',localFormed:false,recovery:'ACTIVE',delivery:'NOT_CONNECTED'};
const tx=(k,p={})=>(t?.[k]??k).replace(/\{(\w+)\}/g,(_,x)=>p[x]??`{${x}}`);const fill=(id,vals)=>{const e=$(id);e.innerHTML=vals.map(v=>`<option value="${v}">${v}</option>`).join('')};const classKey=v=>'class'+v[0]+v.slice(1).toLowerCase();
async function locale(l){delete document.documentElement.dataset.localeSettled;t=await fetch(r.localePaths[l]).then(x=>x.json());state.lang=l;document.documentElement.lang=l;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=tx(e.dataset.i18n));render();document.documentElement.dataset.localeSettled=l}
function row(p){return`<li class="row" data-relationship-ref="${p.relationshipRef}"><b>${tx('person',{n:p.nameNumber})}</b> · ${tx('summary',{class:tx(classKey(p.localClass)),claim:p.counterpartClaim})}</li>`}
function renderEntry(){const e=entryView(r,state.entry);$('#resourceRef').textContent=e.targetResourceRef;$('#entryStatus').textContent=tx(e.previewOnly?'entryPreview':'entryCurrent');$('#entryToggle').textContent=tx(e.previewOnly?'restoreEntry':'previewEntry');$('#entryToggle').dataset.preview=String(e.previewOnly);const c=compareEntryRebind(r,r.entryPolicy.activeEntryBindingRef,r.entryPolicy.previewEntryBindingRef);if(!c.resourceStable||!c.screenStable||!c.routeStable)throw Error('entry drift')}
function openBooklet(){const x=$('#booklet'),b=$('#openBooklet');x.hidden=false;if(b)b.setAttribute('aria-expanded','true');$('#closeBooklet').focus()}
function closeBooklet(){const x=$('#booklet'),b=$('#openBooklet');x.hidden=true;if(b){b.setAttribute('aria-expanded','false');b.focus()}}
function openConnect(){const x=$('#connectPanel');x.hidden=false;$('#connect').setAttribute('aria-expanded','true');x.focus()}
function closeConnect(){const x=$('#connectPanel');x.hidden=true;$('#connect').setAttribute('aria-expanded','false');$('#connect').focus()}
function render(){if(!r||!t)return;renderEntry();const p=project(r,state.count,state.page),host=$('#projection');host.innerHTML='';if(!state.count)host.innerHTML=`<div class="empty"><h3>${tx('emptyTitle')}</h3><p>${tx('emptyBody')}</p></div>`;else{const d=document.createElement('div');d.className='direct';d.innerHTML=`<h3>${tx(p.mode==='DIRECT'?'direct':'pinned')}</h3>`+p.direct.map(x=>`<article class="person" data-relationship-ref="${x.relationshipRef}"><b>${tx('person',{n:x.nameNumber})}</b><span>${tx('summary',{class:tx(classKey(x.localClass)),claim:x.counterpartClaim})}</span></article>`).join('');host.append(d);if(p.mode==='AGGREGATE'){const a=document.createElement('div');a.className='aggregates';a.innerHTML=`<button type="button" class="aggregate" id="openBooklet" aria-controls="booklet" aria-expanded="${String(!$('#booklet').hidden)}"><b>${tx('friends',{count:p.counts.friends})}</b><span>${tx('booklet')}</span></button><div class="aggregate"><b>${tx('groups',{count:p.counts.groups})}</b></div><div class="aggregate"><b>${tx('invitations',{count:p.counts.invitations})}</b></div>`;host.append(a);$('#openBooklet').onclick=openBooklet}else if(!$('#booklet').hidden)$('#booklet').hidden=true}$('#bookletList').innerHTML=p.booklet.rows.map(row).join('');$('#accessibleList').innerHTML=p.accessibleRows.map(row).join('')||`<li>${tx('noRelationships')}</li>`;$('#page').textContent=tx('page',{page:p.booklet.page,pages:p.booklet.pages,shown:p.booklet.rows.length,total:p.booklet.total});$('#prev').disabled=p.booklet.page===1;$('#next').disabled=p.booklet.page===p.booklet.pages;$('#virtual').textContent=p.virtualizationRequired?tx('virtual'):'';$('#delivery').value=state.delivery;$('#delivery').disabled=!canAdvance(state);$('#deliveryStatus').textContent=$('#delivery').disabled?tx('deliveryHeld'):state.delivery;$('#ladder').innerHTML=r.deliveryStates.map(x=>`<li class="${x===state.delivery?'current':''}">${x}</li>`).join('');$('#recoveryStatus').textContent=tx(state.recovery==='ACTIVE'?'active':state.recovery.toLowerCase())}
function gate(){const g=admission(state);$('#form').disabled=!g.admitted;$('#connectStatus').textContent=tx(g.admitted?'ready':'held',{reasons:g.reasons.join(', ')})}
async function boot(){r=validateRegistry(await fetch(REG).then(x=>x.json()));state.entry=r.entryPolicy.activeEntryBindingRef;fill('#method',r.invitation.methods);fill('#invitation',r.invitation.states);fill('#identity',r.invitation.identityStates);fill('#decision',r.invitation.decisions);fill('#localClass',['FRIEND','FAMILY','COLLABORATOR','OTHER']);fill('#delivery',r.deliveryStates);await locale('en');$('#language').onchange=e=>locale(e.target.value);$('#count').onchange=e=>{state.count=+e.target.value;state.page=1;$('#booklet').hidden=true;render()};$('#entryToggle').onclick=()=>{state.entry=$('#entryToggle').dataset.preview==='true'?r.entryPolicy.activeEntryBindingRef:r.entryPolicy.previewEntryBindingRef;render()};$('#connect').onclick=openConnect;$('#closeConnect').onclick=closeConnect;$('#closeBooklet').onclick=closeBooklet;['invitation','identity','decision','localClass'].forEach(id=>$('#'+id).onchange=e=>{state[id]=e.target.value;state.localFormed=false;state.delivery='NOT_CONNECTED';gate();render()});$('#form').onclick=()=>{state.localFormed=true;$('#connectStatus').textContent=`${tx('formed')} ${tx(classKey(state.localClass))}`;render()};$('#delivery').onchange=e=>{if(canAdvance(state))state.delivery=e.target.value;render()};$('#prev').onclick=()=>{state.page--;render()};$('#next').onclick=()=>{state.page++;render()};$('#vex').onclick=()=>{const x=$('#vexText'),show=x.hidden;x.hidden=!show;$('#vex').setAttribute('aria-expanded',String(show));$('#vex').textContent=tx(show?'vexHide':'vexShow')};document.querySelectorAll('[data-recovery]').forEach(b=>b.onclick=()=>{state=recover(state,b.dataset.recovery);gate();render()});gate();render();document.documentElement.dataset.relationshipsReady='true'}boot();
