const ok=(x,m)=>{if(!x)throw new Error(m)};
export function validateRegistry(r){ok(r?.schemaVersion==='vexlife.relationships-browser/v2','schema');ok(r.resource?.stableAcrossEntryRebind===true,'resource');ok(r.discoveryMode==='INVITE_ONLY'&&!r.publicSearch&&!r.communitySearch,'discovery');ok(Object.values(r.effects||{}).every(x=>x===false),'effects');const p=r.projectionPolicy;ok(p.directPersonNodeLimit===5&&p.aggregationThreshold===6&&p.bookletPageSize===20&&p.virtualizationThreshold===100,'thresholds');ok(JSON.stringify(r.invitation?.decisions)===JSON.stringify(['ACCEPT','NARROW','DEFER','DENY','BLOCK']),'decisions');ok(new Set(r.entryBindings.map(x=>x.entryBindingRef)).size===r.entryBindings.length,'entries');return r}
export const people=n=>Array.from({length:n},(_,i)=>({personRef:`person.synthetic.${i+1}`,relationshipRef:`relationship.synthetic.${i+1}`,nameNumber:i+1,localClass:i%4===0?'FAMILY':'FRIEND',counterpartClaim:i%3===0?'NOT_DISCLOSED':'UNKNOWN',pinned:i<2,recentRank:i}));
export function entryView(r,ref=r.entryPolicy.activeEntryBindingRef){validateRegistry(r);const e=r.entryBindings.find(x=>x.entryBindingRef===ref);ok(e,'entry');return {...e,targetResourceRef:r.resource.resourceRef,targetScreenRef:r.resource.screenRef,targetRouteRef:r.resource.routeRef}}
export function compareEntryRebind(r,a,b){const x=entryView(r,a),y=entryView(r,b);return{resourceStable:x.targetResourceRef===y.targetResourceRef,screenStable:x.targetScreenRef===y.targetScreenRef,routeStable:x.targetRouteRef===y.targetRouteRef,sourceChanged:x.sourceResourceRef!==y.sourceResourceRef,identityMigrationRequired:false}}
export function project(r,count,page=1){validateRegistry(r);ok(r.scenarioCounts.includes(count),'count');const all=people(count),p=r.projectionPolicy,pages=Math.max(1,Math.ceil(count/p.bookletPageSize)),resolved=Math.min(Math.max(1,page),pages),start=(resolved-1)*p.bookletPageSize;return{mode:count<p.aggregationThreshold?'DIRECT':'AGGREGATE',direct:count<p.aggregationThreshold?all:all.slice(0,p.directPinnedOrRecentLimitAfterAggregation),counts:{people:count,groups:count?Math.max(1,Math.floor(count/8)):0,invitations:count?Math.min(3,Math.ceil(count/12)):0},booklet:{page:resolved,pages,total:count,rows:all.slice(start,start+p.bookletPageSize)},accessibleRows:all,virtualizationRequired:count>=p.virtualizationThreshold}}
export function admission(s){const reasons=[];if(s.invitation!=='RECEIVED_VERIFIED_REFERENCE')reasons.push('INVITATION_NOT_VERIFIED');if(s.identity!=='VERIFIED_CURRENT')reasons.push('IDENTITY_NOT_CURRENT');if(!['ACCEPT','NARROW'].includes(s.decision))reasons.push('DECISION_NOT_AFFIRMATIVE');if(s.recovery!=='ACTIVE')reasons.push('RECOVERY_HELD');return{admitted:!reasons.length,reasons}}
export const canAdvance=(s)=>s.localFormed===true&&admission(s).admitted;
export function recover(s,action){const n={...s,delivery:'NOT_CONNECTED'};if(action==='RESET_REFERENCE')return{...n,recovery:'ACTIVE',localFormed:false};return{...n,recovery:action==='BLOCK'?'BLOCKED':action==='REVOKE'?'REVOKED':action==='WITHDRAW'?'WITHDRAWN':'DISCONNECTED'}}
