export async function runLivedDDisclosureProof({ app, helpers:{ delay, assert }, viewportClass='DESKTOP' }) {
  const checks=[];
  const details=document.querySelector('#terrainInstrumentation'),summary=document.querySelector('#terrainInstrumentationToggle'),panel=document.querySelector('#terrainInstrumentationPanel');
  const hud=document.querySelector('#terrainHud'),scope=document.querySelector('#terrainScopeChip'),intent=document.querySelector('#terrainIntentTracker'),enabled=document.querySelector('#terrainAutoEntryEnabled'),rawVisibility=document.querySelector('#terrainAutoEntryVisibility'),rawConfidence=document.querySelector('#terrainAutoEntryConfidence'),rawStatus=document.querySelector('#terrainAutoEntryStatus');
  assert(details&&summary&&panel&&hud&&scope&&intent&&enabled&&rawVisibility&&rawConfidence&&rawStatus,'LD00 Terrain instrumentation disclosure fixture incomplete');
  assert(details.open===false,'LD01 cold Terrain deep instrumentation is not collapsed by default');
  assert(rawVisibility.getClientRects().length===0&&rawConfidence.getClientRects().length===0&&hud.getClientRects().length===0&&scope.getClientRects().length===0,'LD01 closed deep instrumentation remains visibly rendered');
  for(const selector of ['#terrainZoomIn','#terrainZoomOut','#terrainAutoEntryEnabled','#terrainFullJourneyToggle','#vexSummon'])assert(document.querySelector(selector)?.getClientRects().length,'LD02 ordinary Terrain lost findable control '+selector);
  const reset=document.querySelector('#terrainReset');assert(reset?.dataset.nodeRef==='element.terrain.reset','LD02 canonical Terrain reset identity is unavailable');
  if(viewportClass==='DESKTOP')assert(reset.getClientRects().length,'LD02 desktop Terrain lost direct reset recovery control');
  else{const menu=document.querySelector('#surfaceMenuButton'),center=document.querySelector('#terrainCenter');assert(menu?.getClientRects().length&&center,'LD02 compact Terrain recovery menu route unavailable');menu.click();await delay(10);assert(center.getClientRects().length,'LD02 compact Terrain did not reveal center-current-context recovery route');menu.click();await delay(10);}
  assert(enabled.getClientRects().length&&rawStatus.getClientRects().length===0,'LD03 auto-entry opt-out is not ordinary while raw V/C status remains deep');
  const frameBefore=JSON.stringify(app.navigation.semanticFrame()),journeyBefore=JSON.stringify(app.navigation.fullJourney()),terrainBefore=app.terrain.currentRef(),autoBefore=JSON.stringify(app.terrain.viewportProjection().semanticAutoEntry);
  summary.focus();summary.click();await delay(20);
  assert(details.open===true&&panel.getClientRects().length&&hud.getClientRects().length&&scope.getClientRects().length&&rawVisibility.getClientRects().length&&rawConfidence.getClientRects().length&&rawStatus.getClientRects().length,'LD04 explicit disclosure did not expose complete deep instrumentation');
  if(viewportClass==='COMPACT'){const r=details.getBoundingClientRect();assert(innerWidth<=760&&r.left>=0&&r.right<=innerWidth+1&&r.width>=220&&r.height<=innerHeight*.72,'LD13 compact disclosure geometry unusable: '+JSON.stringify({innerWidth,innerHeight,left:r.left,right:r.right,width:r.width,height:r.height}));}
  rawVisibility.focus();assert(document.activeElement===rawVisibility,'LD06 revealed raw control is not keyboard focusable');summary.focus();summary.click();await delay(10);
  assert(details.open===false&&document.activeElement===summary,'LD07 collapse did not deterministically return focus to the disclosure control');
  assert(rawVisibility.getClientRects().length===0&&rawConfidence.getClientRects().length===0,'LD06 collapsed deep descendants remain keyboard/render targets');
  assert(JSON.stringify(app.navigation.semanticFrame())===frameBefore&&JSON.stringify(app.navigation.fullJourney())===journeyBefore&&app.terrain.currentRef()===terrainBefore&&JSON.stringify(app.terrain.viewportProjection().semanticAutoEntry)===autoBefore,'LD05 disclosure mutated semantic current context, Journey, Terrain ref, or auto-entry values');
  const chatProjects=document.querySelector('#openWorkspace'),projectSummary=document.querySelector('#projectRail summary'),manual=document.querySelector('[data-terrain-context="workspace"]'),badge=document.querySelector('#terrainWorkspaceBadge');
  assert(chatProjects&&projectSummary&&manual&&badge,'LD08 disclosure terminology fixtures unavailable');
  assert(chatProjects.textContent.trim()===projectSummary.textContent.trim()&&manual.textContent.trim()!==chatProjects.textContent.trim(),'LD08 Chat source descent and Terrain manual layout still share one visible mental model');
  const manualBefore=app.terrain.viewportProjection().workspaceMode,toggled=app.terrain.toggleWorkspace();assert(toggled!==manualBefore&&badge.classList.contains('show')===toggled,'LD09 existing Terrain manual-layout behavior or visible state drifted');const restored=app.terrain.toggleWorkspace();assert(restored===manualBefore,'LD09 manual-layout state did not restore');
  for(const lang of ['en','ja','zh']){const response=await fetch('../../blueprint/strings/'+lang+'.json');assert(response.ok,'LD10 '+lang+' localization catalog unavailable');const catalog=await response.json(),detailLabel=catalog['terrain.instrumentation.summary'],manualLabel=catalog['terrain.manual-layout'],projectsLabel=catalog['region.projects.label'];assert(detailLabel&&manualLabel&&projectsLabel,'LD10 '+lang+' disclosure/manual-layout localization fallback');assert(detailLabel!==manualLabel&&manualLabel!==projectsLabel,'LD08 '+lang+' disclosure/manual/source-descent concepts collapsed');}
  const style=getComputedStyle(details);assert(style.transitionDuration==='0s'||style.transitionProperty==='all'||!style.transitionProperty,'LD11 disclosure meaning unexpectedly depends on animated details state');
  checks.push('LD01 cold Terrain collapses deep HUD/scope/raw V-C/intent instrumentation by default','LD02-LD03 ordinary Terrain retains semantic depth/zoom/recovery/Journey/Vex and auto-entry opt-out','LD04-LD07 native explicit disclosure is complete, semantic-state neutral, keyboard-safe and focus deterministic','LD08-LD10 Chat Projects, Terrain manual layout and deep Terrain details remain distinct in EN/JA/ZH','LD11 disclosure meaning is motion independent',viewportClass==='COMPACT'?'LD13 compact viewport executes the same disclosure proof without a microscopic always-visible rack':'LD12 desktop owner-domain Terrain suite carries LIVED-D fail-closed proof');
  return {proofRef:'proof.vexlife.e28.lived-d.progressive-disclosure/v1',state:'PASS',viewportClass,checks};
}

export async function runQ7AdaptationProof({ app, helpers:{ delay, assert, geometryDifferences, geometryIdentity } }) {
  const checks=[];
  const menuButton=document.querySelector('#surfaceMenuButton'),why=document.querySelector('#terrainAdaptationWhy'),whySummary=why?.querySelector('summary'),reason=document.querySelector('#terrainAdaptationReason'),undo=document.querySelector('#terrainAdaptationUndo'),preference=document.querySelector('#terrainAdaptiveLayoutEnabled');
  assert(menuButton&&why&&whySummary&&reason&&undo&&preference,'Q7-00 adaptation control fixture incomplete');
  const frameBefore=JSON.stringify(app.navigation.semanticFrame()),journeyBefore=JSON.stringify(app.navigation.fullJourney()),baselineGeometry=app.terrain.geometrySnapshot(),baselineIdentity=geometryIdentity(baselineGeometry),baseline=app.terrain.adaptationSnapshot();
  const status=()=>document.querySelector('[data-node-ref="element.terrain.adaptation-state"]');
  assert(baseline.enabled===true&&baseline.stateClass==='ADAPTIVE'&&status()?.getClientRects().length&&status().textContent.trim(),'Q7-01 ordinary Terrain does not expose truthful adaptation state');
  const allowedReasons=new Set(['CURRENT_CONTEXT','USER_MANUAL_OVERRIDE','CURRENT_WORK','CURRENT_SCOPE','STRUCTURAL_CONTEXT','ADAPTIVE_LAYOUT_DISABLED','ADAPTATION_UNDONE_FOR_CURRENT_CONTEXT']);assert(allowedReasons.has(baseline.reasonCode),'Q7-02 observable reason escaped closed product vocabulary: '+baseline.reasonCode);
  menuButton.click();await delay(10);const preferenceTarget=preference.closest('label');assert(whySummary.getClientRects().length&&undo.getClientRects().length&&preference.getClientRects().length&&preferenceTarget?.getClientRects().length,'Q7-10 adaptation controls are not findable through the existing surface route');for(const target of [whySummary,undo,preferenceTarget])assert(target.getBoundingClientRect().height>=44,'Q7-10 adaptation interactive target below 44px');
  whySummary.focus();whySummary.click();await delay(10);assert(why.open&&reason.textContent.trim()&&!/chain.of.thought|model reasoning|private reasoning/i.test(reason.textContent),'Q7-02 why-this-layout exposed no closed product reason');whySummary.click();await delay(10);assert(!why.open&&JSON.stringify(app.navigation.semanticFrame())===frameBefore&&JSON.stringify(app.navigation.fullJourney())===journeyBefore,'Q7-09 explanation disclosure changed semantic state or Journey');
  const storageBeforeUndo=localStorage.getItem('vexlife.terrain.layout');if(baseline.undoAvailable){undo.focus();undo.click();await delay(30);const suppressed=app.terrain.adaptationSnapshot(),suppressedGeometry=app.terrain.geometrySnapshot(),storedSuppressed=JSON.parse(localStorage.getItem('vexlife.terrain.layout')||'{}');assert(suppressed.suppressedForCurrentContext&&suppressed.stateClass==='UNDONE'&&suppressed.reasonCode==='ADAPTATION_UNDONE_FOR_CURRENT_CONTEXT','Q7-04 undo did not enter transient current-context suppression');assert(suppressedGeometry.nodes.every(node=>node.role==='PERIPHERAL_CONTEXT'||node.role==='MANUAL_OVERRIDE'),'Q7-04 automatic child-role adaptation remained after undo');assert(storedSuppressed.adaptation?.enabled===true&&!Object.hasOwn(storedSuppressed.adaptation||{},'runtime'),'Q7-06 transient suppression crossed persistence boundary');assert(localStorage.getItem('vexlife.terrain.layout')===storageBeforeUndo,'Q7-06 undo rewrote persistent Terrain layout');assert(JSON.stringify(app.navigation.semanticFrame())===frameBefore&&JSON.stringify(app.navigation.fullJourney())===journeyBefore,'Q7-04 undo rewrote semantic current context or Journey');const restore=document.querySelector('#terrainAdaptationUndo');assert(restore.dataset.adaptationRoute==='RESTORE','Q7-05 same recovery control did not invert to restore route');restore.click();await delay(30);assert(!app.terrain.adaptationSnapshot().suppressedForCurrentContext,'Q7-05 inverse restore route did not clear transient suppression state');let restoreDiffs=geometryDifferences(baselineGeometry,app.terrain.geometrySnapshot());for(let settleAttempt=0;settleAttempt<40&&restoreDiffs.length;settleAttempt++){await delay(20);restoreDiffs=geometryDifferences(baselineGeometry,app.terrain.geometrySnapshot())}assert(restoreDiffs.length===0,'Q7-05 inverse restore route did not recover deterministic automatic geometry after bounded visual settle: '+JSON.stringify(restoreDiffs.slice(0,8)));}
  preference.checked=false;preference.dispatchEvent(new Event('change',{bubbles:true}));await delay(30);let snap=app.terrain.adaptationSnapshot(),stored=JSON.parse(localStorage.getItem('vexlife.terrain.layout')||'{}');assert(snap.enabled===false&&snap.stateClass==='ADAPTATION_OFF'&&snap.reasonCode==='ADAPTIVE_LAYOUT_DISABLED','Q7-07 preference off did not disable automatic adaptation');assert(stored.adaptation?.enabled===false&&!Object.hasOwn(stored.adaptation||{},'runtime'),'Q7-07 persistent preference boundary is malformed');const pinTarget=app.terrain.childRefs()[0];assert(pinTarget,'Q7-03 requires one child for manual-override precedence');app.terrain.toggleManualPin(pinTarget);snap=app.terrain.adaptationSnapshot();assert(snap.stateClass==='PINNED'&&snap.manualOverrideRef===pinTarget&&snap.reasonCode==='USER_MANUAL_OVERRIDE','Q7-03 manual override did not outrank preference-off automatic state');app.terrain.toggleManualPin(pinTarget);
  app.terrain.setAdaptationSuppressed(false);app.terrain.reset();snap=app.terrain.adaptationSnapshot();assert(snap.enabled===false&&!snap.suppressedForCurrentContext,'Q7-08 Reset failed to clear transient suppression while preserving preference');preference.checked=true;preference.dispatchEvent(new Event('change',{bubbles:true}));await delay(30);snap=app.terrain.adaptationSnapshot();assert(snap.enabled===true&&snap.stateClass==='ADAPTIVE','Q7-07 re-enable did not restore adaptive state');stored=JSON.parse(localStorage.getItem('vexlife.terrain.layout')||'{}');assert(stored.adaptation?.enabled===true&&!Object.hasOwn(stored.adaptation||{},'runtime'),'Q7-06/Q7-07 restored preference persistence malformed');
  for(const lang of ['en','ja','zh']){const response=await fetch('../../blueprint/strings/'+lang+'.json');assert(response.ok,'Q7-11 '+lang+' catalog unavailable');const catalog=await response.json();for(const key of ['terrain.adaptation.state','terrain.adaptation.status.adaptive','terrain.adaptation.status.pinned','terrain.adaptation.status.undone','terrain.adaptation.status.off','terrain.adaptation.why','terrain.adaptation.undo','terrain.adaptation.restore','terrain.adaptation.preference','terrain.adaptation.reason.current-work','terrain.adaptation.reason.current-scope','terrain.adaptation.reason.structural','terrain.adaptation.reason.disabled','terrain.adaptation.reason.undone'])assert(catalog[key]&&!catalog[key].startsWith('terrain.'),'Q7-11 '+lang+' localization fallback '+key)}
  menuButton.click();await delay(10);assert(JSON.stringify(app.navigation.semanticFrame())!==''&&app.terrain.adaptationSnapshot().enabled===true,'Q7 final state unavailable');
  checks.push('Q7-01/Q7-02 visible adaptation state and why-this-layout use closed observable product reasons','Q7-03 manual override remains highest precedence','Q7-04/Q7-05 one reversible suppression route provides undo and exact restore without Journey rewrite','Q7-06/Q7-08 transient runtime state stays out of persistence while Reset preserves explicit preference','Q7-07 adaptive-layout preference persists explicitly and reversibly','Q7-09/Q7-12 explanation and recovery meaning are presentation-state based, not motion/private reasoning','Q7-10/Q7-11 stable accessible controls and EN/JA/ZH labels remain complete');
  return {proofRef:'proof.vexlife.e28.q7.intelligence-visible-adaptation/v1',state:'PASS',checks};
}

export async function runQ2MobileGrammarProof({ app, helpers:{ delay, assert } }) {
  const checks=[];
  const frameBefore=JSON.stringify(app.navigation.semanticFrame()),journeyBefore=JSON.stringify(app.navigation.fullJourney()),adaptationBefore=JSON.stringify(app.terrain.adaptationSnapshot()),currentBefore=app.terrain.currentRef();
  const projection=app.terrain.viewportProjection();assert(projection.viewportClass==='COMPACT'&&projection.projectionGrammar==='MOBILE_STACK','M02 compact Terrain did not enter MOBILE_STACK grammar: '+JSON.stringify(projection));
  const focus=document.querySelector('#terrainFocus'),world=document.querySelector('#terrainWorld'),focusRect=focus?.getBoundingClientRect();assert(focus&&world&&focusRect,'M03 compact current focus fixture unavailable');
  assert(focusRect.left>=-1&&focusRect.right<=innerWidth+1&&focusRect.width>=innerWidth*.72,'M03 compact current context is still a miniature or clipped desktop focus: '+JSON.stringify({innerWidth,left:focusRect.left,right:focusRect.right,width:focusRect.width}));
  const matrix=new DOMMatrix(getComputedStyle(world).transform);assert(matrix.a>=.75,'M02 compact Terrain still downscales the desktop world: '+matrix.a);
  const nodes=[...document.querySelectorAll('.e27-node')],visible=nodes.filter(node=>{const r=node.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth});assert(visible.length>=1,'M04 mobile stack exposes no surrounding context');
  let priorTop=-Infinity;for(const node of visible){const r=node.getBoundingClientRect();assert(node.dataset.terrainRef&&node.dataset.adaptiveGeometry&&node.dataset.relevanceReason,'M05 compact context occurrence lost stable semantic/adaptation truth');assert(r.height>=44&&r.left>=-1&&r.right<=innerWidth+1,'M11 compact context target unusable: '+node.dataset.terrainRef);assert(r.top>=priorTop-1,'M04 mobile context occurrences are not a deterministic vertical/layered reveal');priorTop=r.top;assert(Math.abs((r.left+r.right)/2-(focusRect.left+focusRect.right)/2)<=innerWidth*.28,'M04 compact context escaped the mobile stack axis');}
  assert(document.documentElement.scrollWidth<=innerWidth+1,'M14 compact Terrain introduced horizontal page overflow');
  for(const selector of ['#terrainZoomIn','#terrainZoomOut','#terrainFullJourneyToggle','#surfaceMenuButton','#vexSummon'])assert(document.querySelector(selector),'M08/M09/M10 compact owner route missing '+selector);
  assert(JSON.stringify(app.navigation.semanticFrame())===frameBefore&&JSON.stringify(app.navigation.fullJourney())===journeyBefore&&JSON.stringify(app.terrain.adaptationSnapshot())===adaptationBefore&&app.terrain.currentRef()===currentBefore,'M06/M07 compact projection mutated semantic/Journey/Q7 state');
  await delay(20);checks.push('M02 compact viewport uses MOBILE_STACK rather than shrunk desktop world','M03 current context remains dominant and horizontally usable','M04-M05 surrounding context is a stable-ref vertical/layered reveal preserving adaptation truth','M06-M07 compact projection preserves semantic current context, Journey and Q7 state','M08-M10 LIVED-D/Journey/Vex owner routes remain present without owner expansion','M11/M12 compact interaction meaning is accessible and motion-independent','M14 compact page has no horizontal overflow');
  return{proofRef:'proof.vexlife.e28.q2.mobile-native-spatial-grammar/v1',state:'PASS',viewportClass:'COMPACT',projectionGrammar:'MOBILE_STACK',checks};
}

export async function runTerrainZoomTargetRegressionProof({ app, helpers:{ delay, assert } }) {
  const checks=[];
  const rootRef=app.terrain.rootRef;
  const rootChildren=app.terrain.childRefs(rootRef);
  const firstRef=rootChildren[0]??null;
  const targetRef=rootChildren.find((ref,index)=>index>0&&document.querySelector(`.e27-node[data-terrain-ref="${CSS.escape(ref)}"]`))??null;
  const terrain=document.querySelector('#view-terrain');
  const originalAuto=structuredClone(app.terrain.viewportProjection().semanticAutoEntry);
  assert(rootRef&&firstRef&&targetRef&&terrain,'TREG-00 Terrain zoom-target fixture incomplete');
  const resetRoot=async()=>{app.terrain.reset();await delay(90);assert(app.terrain.currentRef()===rootRef,'TREG cleanup did not restore canonical root');};
  const pointForRef=(ref)=>{const node=document.querySelector(`.e27-node[data-terrain-ref="${CSS.escape(ref)}"]`);assert(node?.getClientRects().length,`TREG rendered target unavailable: ${ref}`);const r=node.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2};};
  const wheelAt=async(point,{steps=3,deltaY=-180}={})=>{for(let index=0;index<steps;index++){terrain.dispatchEvent(new WheelEvent('wheel',{bubbles:true,cancelable:true,clientX:point().x,clientY:point().y,deltaY}));await delay(45);}await delay(520);return app.terrain.currentRef();};
  const wheelToward=(ref,options)=>wheelAt(()=>pointForRef(ref),options);
  const emptyPoint=()=>{const r=terrain.getBoundingClientRect(),fractions=[[.84,.78],[.16,.78],[.84,.24],[.16,.24],[.5,.82]];for(const [fx,fy] of fractions){const point={x:r.left+r.width*fx,y:r.top+r.height*fy};const occupied=document.elementsFromPoint(point.x,point.y).some((element)=>element.closest?.('.e27-node,.e27-focus,.e27-vex'));if(!occupied)return point;}return null;};
  try{
    await resetRoot();app.terrain.setAutoEntryEnabled(true);app.terrain.setAutoEntryThresholds({visibilityThreshold:.72,confidenceThreshold:.8});
    await wheelToward(targetRef);assert(app.terrain.currentRef()===targetRef,`TREG-01/TREG-02 zoom anchored on non-first child committed ${app.terrain.currentRef()} instead of ${targetRef}`);const exactJourney=app.navigation.fullJourney().at(-1);assert(exactJourney?.after?.selectedNodeRef===targetRef,'TREG-08 exact zoom destination was not preserved in Journey');checks.push('TREG-01/TREG-02 rendered non-first child under the zoom anchor is the exact semantic destination','TREG-08 zoom destination and Journey semantic destination remain identical');

    await resetRoot();const empty=emptyPoint();assert(empty,'TREG-03 no empty Terrain anchor could be established');await wheelAt(()=>empty);assert(app.terrain.currentRef()===rootRef,'TREG-03 empty-space zoom invented a semantic child entry');checks.push('TREG-03 empty-space zoom never invents a child destination');

    await resetRoot();app.terrain.setAutoEntryThresholds({visibilityThreshold:.5,confidenceThreshold:.9});await wheelToward(firstRef,{steps:1,deltaY:-120});await wheelToward(targetRef,{steps:1,deltaY:-120});assert(app.terrain.currentRef()===rootRef,'TREG-04 candidate switch carried stale confidence into a semantic entry');await wheelToward(targetRef,{steps:2,deltaY:-120});assert(app.terrain.currentRef()===targetRef,'TREG-04 candidate-specific intent did not converge on the switched-to target');checks.push('TREG-04 changing the approached child resets stale intent and later converges only on the new candidate');

    await resetRoot();app.terrain.setAutoEntryEnabled(false);await wheelToward(targetRef,{steps:4,deltaY:-180});assert(app.terrain.currentRef()===rootRef&&app.state.terrain.autoEntry.lastEvaluation?.reason==='OPTED_OUT','TREG-05 auto-entry opt-out did not block zoom semantic entry');checks.push('TREG-05 explicit auto-entry opt-out blocks the same zoom route');

    await resetRoot();app.terrain.setAutoEntryEnabled(true);app.terrain.setAutoEntryThresholds({visibilityThreshold:.5,confidenceThreshold:1});await wheelToward(targetRef,{steps:2,deltaY:-120});assert(app.terrain.currentRef()===rootRef&&app.state.terrain.autoEntry.lastEvaluation?.reason==='CONFIDENCE_BELOW_THRESHOLD','TREG-06 configured high confidence threshold was not causal');await resetRoot();app.terrain.setAutoEntryThresholds({visibilityThreshold:.5,confidenceThreshold:.5});await wheelToward(targetRef,{steps:2,deltaY:-120});assert(app.terrain.currentRef()===targetRef,'TREG-06 lowering configured confidence threshold did not admit the same target-specific gesture');checks.push('TREG-06 configured visibility/confidence thresholds causally gate the semantic commit');

    await resetRoot();const direct=document.querySelector(`.e27-node[data-terrain-ref="${CSS.escape(targetRef)}"]`);direct.click();await delay(520);assert(app.terrain.currentRef()===targetRef,'TREG-07 direct node activation no longer resolves the exact target');checks.push('TREG-07 direct node activation preserves exact target identity');

    await resetRoot();app.terrain.setAutoEntryThresholds({visibilityThreshold:.72,confidenceThreshold:.8});const realMatchMedia=globalThis.matchMedia;globalThis.matchMedia=(query)=>query.includes('prefers-reduced-motion')?{matches:true,media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return true}}:realMatchMedia(query);try{await wheelToward(targetRef);assert(app.terrain.currentRef()===targetRef,'TREG-09 reduced-motion zoom changed semantic target correspondence');}finally{globalThis.matchMedia=realMatchMedia;}checks.push('TREG-09 reduced-motion uses the same target correspondence without motion-dependent meaning');
  }finally{
    app.terrain.setAutoEntryEnabled(originalAuto.enabled);app.terrain.setAutoEntryThresholds({visibilityThreshold:originalAuto.visibilityThreshold,confidenceThreshold:originalAuto.confidenceThreshold});app.terrain.reset();await delay(90);
  }
  return{proofRef:'proof.vexlife.experience-integrity.terrain-zoom-target-correspondence/v1',state:'PASS',checks};
}

export const terrainSuite = Object.freeze({
  suiteRef:'suite.vexlife.browser.terrain/v1',
  async run({ app, state, helpers:{ delay, assert, assertLiveEdgeAttachments, worldRelationshipClearance, renderedPixelClose, geometryDifferences, geometryIdentity, radialDistance, motionCssToken, transitionProperties, assertSettledGeometry } }) {
    const rootRef = state.rootRef;
    const rootChildren = state.rootChildren;
    assert(rootRef && Array.isArray(rootChildren) && app.terrain.currentRef() === rootRef, 'Terrain suite requires canonical root baseline');
    assert(document.querySelector('#contextSurface').hidden, 'Terrain suite requires contextual surface closed');
    const checks = [];
    const desktopProjection=app.terrain.viewportProjection();assert(desktopProjection.viewportClass==='DESKTOP'&&desktopProjection.projectionGrammar==='SPATIAL_WORLD','M01 desktop Terrain projection grammar drifted: '+JSON.stringify(desktopProjection));checks.push('M01 desktop Terrain remains the accepted SPATIAL_WORLD grammar');
    const livedD=await runLivedDDisclosureProof({app,helpers:{delay,assert},viewportClass:'DESKTOP'});checks.push(...livedD.checks);
    const q7=await runQ7AdaptationProof({app,helpers:{delay,assert,geometryDifferences,geometryIdentity}});checks.push(...q7.checks);
    const terrainRegression=await runTerrainZoomTargetRegressionProof({app,helpers:{delay,assert}});checks.push(...terrainRegression.checks);
    checks.push('TREG-10 the remaining owner-domain Terrain suite must also pass before this suite can return PASS');

    const motionTokens={tactile:motionCssToken('--motion-duration-tactile'),fast:motionCssToken('--motion-duration-fast'),surface:motionCssToken('--motion-duration-surface'),layout:motionCssToken('--motion-duration-layout'),spatial:motionCssToken('--motion-duration-spatial'),exit:motionCssToken('--motion-duration-semantic-exit'),arrive:motionCssToken('--motion-duration-semantic-arrive'),ease:motionCssToken('--motion-ease-responsive')};
    assert(Object.values(motionTokens).every(Boolean),'Q6 shared motion token vocabulary is incomplete');
    const tactileControl=document.querySelector('#terrainReset'),tactileStyle=getComputedStyle(tactileControl);assert(tactileControl&&transitionProperties(tactileStyle).includes('scale'),'Q6 tactile button response is not expressed through independent scale motion');
    const motionJourneyBefore=app.navigation.fullJourney().length;tactileControl.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:77}));tactileControl.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:77}));assert(app.navigation.fullJourney().length===motionJourneyBefore,'Q6 tactile response mutated Journey truth');
    const worldMotionRule=[...document.styleSheets].flatMap((sheet)=>{try{return[...sheet.cssRules]}catch{return[]}}).find((rule)=>rule.selectorText==='.e27-world'),worldMotionDeclaration=worldMotionRule?.style?.transition||'';assert(worldMotionDeclaration.includes('var(--motion-duration-spatial)')&&worldMotionDeclaration.includes('var(--motion-duration-surface)'),'Q6 Terrain world stylesheet is not bound to shared motion tokens');
    const surfaceJourneyBefore=app.navigation.fullJourney().length;app.terrain.openJourney();await delay(70);const drawer=document.querySelector('#terrainJourneyDrawer'),drawerContent=drawer?.querySelector(':scope > .e27-drawer-head'),drawerEarlyStyle=drawerContent?getComputedStyle(drawerContent):null;assert(drawer&&drawer.classList.contains('show')&&drawerEarlyStyle&&drawerEarlyStyle.visibility==='hidden'&&Number(drawerEarlyStyle.opacity)<=.01,'Q6 drawer content was not fully hidden while shell crossed the viewport edge');await delay(120);const drawerLateStyle=getComputedStyle(drawerContent),drawerLateOpacity=Number(drawerLateStyle.opacity);assert(drawerLateStyle.visibility==='visible'&&drawerLateOpacity>.7,'Q6 drawer content did not become visibly revealed after shell entry');app.terrain.closeJourney();await delay(220);assert(app.navigation.fullJourney().length===surfaceJourneyBefore,'Q6 drawer presentation changed Journey truth');
    checks.push('Q6 shared tactile/surface/spatial motion vocabulary is present and presentation-only','Q6 drawer shell enters before content reveal so text is not visibly clipped');

    const canonical = app.terrain.geometrySnapshot();
    assert(canonical.current.role === 'CURRENT_CONTEXT', 'P02 current context geometry role missing');
    const activeSubcontext = canonical.nodes.find((node)=>node.role === 'ACTIVE_SUBCONTEXT' && node.relevanceReason === 'CURRENT_WORK_SUBCONTEXT');
    const peripheral = canonical.nodes.find((node)=>node.role === 'PERIPHERAL_CONTEXT');
    const structuralPeripherals = canonical.nodes.filter((node)=>node.role === 'PERIPHERAL_CONTEXT');
    const structuralPeripheral = structuralPeripherals.find((node)=>app.terrain.childRefs(node.ref).length>0);
    assert(activeSubcontext && peripheral, 'P02 accepted root context must expose one active subcontext occurrence plus structural children');
    const activeEdge=canonical.edges.find((edge)=>edge.ref===activeSubcontext.ref),structuralByX=[...structuralPeripherals].sort((a,b)=>a.left-b.left);
    assert(activeSubcontext.relevanceReason === 'CURRENT_WORK_SUBCONTEXT', 'P02 exact current-work child is not typed as an active subcontext occurrence');
    assert(activeSubcontext.width===peripheral.width && activeSubcontext.height===peripheral.height, 'Q6 active subcontext still masquerades as a wider independent peer component');
    assert(Math.abs(activeSubcontext.left-canonical.current.left)<=.5 && activeSubcontext.top-canonical.current.top>(canonical.current.height+activeSubcontext.height)/2+90, 'Q6 active subcontext is not docked below its current semantic owner');
    assert(activeEdge&&Math.abs(activeEdge.x1-activeEdge.x2)<=1.1, 'Q6 active-subcontext relationship bridge is not vertically anchored to its owner');
    assert(structuralPeripheral, 'P02 descendant-bearing unrelated node was still promoted merely because it has descendants');
    assert(structuralByX.length===3 && Math.abs(structuralByX[0].top-structuralByX[2].top)<=1.1 && Math.abs((structuralByX[0].left+structuralByX[2].left)/2-canonical.current.left)<=1.1 && Math.abs(structuralByX[1].left-canonical.current.left)<=1.1, 'Q6 structural-child orbit is not symmetrically derived after removing the active subcontext occurrence');
    assert(canonical.current.width > activeSubcontext.width && activeSubcontext.width===peripheral.width, 'P02 current context strength or shared child footprint drifted');
    const activeClearance=worldRelationshipClearance(activeSubcontext.ref),peripheralClearances=structuralPeripherals.map((node)=>worldRelationshipClearance(node.ref));
    assert(activeClearance>=94,`P02 active-subcontext Terrain-world boundary clearance collapsed below the spatial floor: ${activeClearance}`);
    assert(peripheralClearances.length===3&&Math.min(...peripheralClearances)>=94,`P02 structural-child clearance collapsed below the spatial floor: ${JSON.stringify(peripheralClearances)}`);
    assertSettledGeometry(canonical,'P04/P05 fan');
    const projectionProofs={fan:canonical};
    for(const mode of ['rings','carousel','fan']){app.terrain.setProjectionMode(mode);const projection=app.terrain.geometrySnapshot();assertSettledGeometry(projection,`P04/P05 ${mode}`);projectionProofs[mode]=projection;}
    assert(geometryIdentity(projectionProofs.fan)===geometryIdentity(canonical),'P03 returning to fan did not restore deterministic canonical geometry');
    const beforeEquivalentJourney = app.navigation.fullJourney().length; app.terrain.render(false); const equivalent = app.terrain.geometrySnapshot();
    assert(geometryIdentity(canonical) === geometryIdentity(equivalent), 'P03 equivalent semantic state produced different geometry');
    assert(app.navigation.fullJourney().length === beforeEquivalentJourney, 'P12 adaptive rerender changed semantic journey');
    assert(document.querySelector('#terrainFocus').textContent.includes('Center is current semantic context.'), 'P06 current context emphasis is not explicit');
    checks.push('P02-P06 adaptive geometry is ordered, deterministic, overlap-free, edge-true, and unmistakably current');

    const journeyBeforePin = app.navigation.fullJourney().length, currentBeforePin = app.terrain.currentRef();
    app.state.terrain.localOffsets[peripheral.ref]={x:34,y:-20}; app.terrain.render(false); const offsetGeometry=app.terrain.geometrySnapshot(),offsetNode=offsetGeometry.nodes.find((node)=>node.ref===peripheral.ref);
    assert(offsetNode.localOffset.x===34 && offsetNode.localOffset.y===-20 && renderedPixelClose(offsetNode.left,peripheral.left+34) && renderedPixelClose(offsetNode.top,peripheral.top-20), 'P12 existing local offset is not truthfully composed over adaptive geometry');
    assert(app.terrain.toggleWorkspace()===true, 'P09 projection workspace did not enter explicit human-control mode');
    const pinControl=document.querySelector(`.e27-node[data-terrain-ref="${peripheral.ref}"]`), beforePinMotion=app.terrain.liveGeometrySnapshot(); pinControl.click();
    await delay(100); const livePin=app.terrain.liveGeometrySnapshot(),livePinnedNode=livePin.nodes.find((node)=>node.ref===peripheral.ref),beforePinnedNode=beforePinMotion.nodes.find((node)=>node.ref===peripheral.ref),beforeYield=beforePinMotion.nodes.find((node)=>node.ref!==peripheral.ref),liveYield=beforeYield?livePin.nodes.find((node)=>node.ref===beforeYield.ref):null;
    assertLiveEdgeAttachments('P09 manual override in-flight');
    assert(livePinnedNode&&beforePinnedNode&&radialDistance(livePinnedNode)<radialDistance(beforePinnedNode)-10,'P09 manual override did not visibly pull the human-prioritized node inward during reflow');
    assert(!beforeYield||!liveYield||radialDistance(liveYield)>radialDistance(beforeYield)+6,'P09 neighboring geometry did not visibly yield to the manual override');
    await delay(280); const pinned = app.terrain.geometrySnapshot(), pinnedNode = pinned.nodes.find((node)=>node.ref===peripheral.ref);
    assert(pinned.manualOverrideRef===peripheral.ref && pinnedNode?.role==='MANUAL_OVERRIDE' && pinnedNode.manualOverride===true, 'P09 manual override did not outrank adaptation');
    assert(pinnedNode.width > peripheral.width, 'P09 manual override did not produce stronger node geometry');
    assert(pinnedNode.localOffset.x===34 && pinnedNode.localOffset.y===-20, 'P12 manual override lost persisted local offset identity');
    app.state.terrain.localOffsets[peripheral.ref]={x:0,y:0}; app.terrain.render(false); const manualBase=app.terrain.geometrySnapshot(),manualBaseNode=manualBase.nodes.find((node)=>node.ref===peripheral.ref);
    assert(manualBaseNode?.role==='MANUAL_OVERRIDE' && renderedPixelClose(pinnedNode.left,manualBaseNode.left+34) && renderedPixelClose(pinnedNode.top,manualBaseNode.top-20), 'P12 local offset is not truthfully additive over the manual-override adaptive base');
    app.state.terrain.localOffsets[peripheral.ref]={x:34,y:-20}; app.terrain.render(false); const restoredPinned=app.terrain.geometrySnapshot();
    assert(geometryIdentity(restoredPinned)===geometryIdentity(pinned), 'P12 restoring the same local offset did not recover deterministic manual-override geometry');
    assert(app.navigation.fullJourney().length===journeyBeforePin && app.terrain.currentRef()===currentBeforePin, 'P12 manual geometry override changed semantic refs or journey');
    assert(pinControl.dataset.manualOverride==='true' || document.querySelector(`.e27-node[data-terrain-ref="${peripheral.ref}"]`).dataset.manualOverride==='true', 'P09 pinned state is not visibly distinguishable in rendered node state');
    const journeyBeforeReset=app.navigation.fullJourney().length; app.terrain.reset(); const resetGeometry=app.terrain.geometrySnapshot(); await delay(100); const resetActiveSubcontextClearanceWorld=worldRelationshipClearance(activeSubcontext.ref); assert(resetActiveSubcontextClearanceWorld>=90,`P10 reset choreography collapsed active-subcontext Terrain-world boundary clearance: ${resetActiveSubcontextClearanceWorld}`);
    assert(resetGeometry.manualOverrideRef===null && Object.keys(app.state.terrain.localOffsets).length===0, 'P10 reset did not clear bounded manual geometry state');
    const canonicalResetNode=canonical.nodes.find((node)=>node.ref===peripheral.ref),resetDuringNode=resetGeometry.nodes.find((node)=>node.ref===peripheral.ref);
    assert(canonicalResetNode&&resetDuringNode&&resetDuringNode.role===canonicalResetNode.role&&resetDuringNode.relevanceReason===canonicalResetNode.relevanceReason,'P10 reset did not restore canonical semantic geometry state before visual settlement');
    assert(resetDuringNode.width>canonicalResetNode.width+20&&resetDuringNode.height>canonicalResetNode.height+20,'P10 reset recovery animation did not visibly depart from the prior manual geometry toward canonical geometry');
    await delay(380); const settledResetGeometry=app.terrain.geometrySnapshot(),resetDifferences=geometryDifferences(canonical,settledResetGeometry); assert(resetDifferences.length===0, `P10 reset did not settle to canonical adaptive choreography: ${JSON.stringify(resetDifferences.slice(0,12))}`);
    assert(app.navigation.fullJourney().length===journeyBeforeReset && app.terrain.currentRef()===currentBeforePin, 'P12 pure geometry reset changed semantic journey or current context');
    checks.push('P09-P12 bounded manual override wins, local offset stays truthful, reset recovers canonical choreography, semantic refs stay stable');


    const q4TargetRef=app.terrain.childRefs()[0]||null;assert(q4TargetRef,'Q4 requires one semantic child for historical revisit proof');
    await app.terrain.travel(q4TargetRef,'in');const q4TargetEvent=app.navigation.fullJourney().at(-1);assert(q4TargetEvent?.after?.selectedNodeRef===q4TargetRef,'Q4 target journey event did not capture semantic child frame');await app.terrain.up();
    const q4HistoryBeforeScrub=app.navigation.fullJourney(),q4HistoryBeforeScrubJson=JSON.stringify(q4HistoryBeforeScrub),q4CurrentBeforeScrub=JSON.stringify(app.navigation.semanticFrame()),q4TargetIndex=q4HistoryBeforeScrub.findIndex(event=>event.journeyRef===q4TargetEvent.journeyRef);assert(q4TargetIndex>=0,'Q4 target journey event identity was not retained');
    app.terrain.openJourney();const q4Projection=app.terrain.setJourneyScrubIndex(q4TargetIndex);assert(JSON.stringify(app.navigation.semanticFrame())===q4CurrentBeforeScrub&&JSON.stringify(app.navigation.fullJourney())===q4HistoryBeforeScrubJson,'Q4 scrub cursor changed canonical current context or immutable Journey');assert(q4Projection.transitionReason===q4TargetEvent.actionRef&&q4Projection.clusters.length>0,'Q4 scrub projection lost transition provenance or conceptual clusters');const q4Marker=document.querySelector('#terrainJourneyCurrentMarker'),q4CanonicalLabel=document.querySelector('#terrainFocus h2')?.textContent?.trim(),q4BrowsedLabel=document.querySelector('#terrainJourneyList .history-entry[aria-current="true"] strong')?.textContent?.trim();assert(q4Marker?.dataset.historyMode==='browsing'&&app.terrain.currentRef()===rootRef&&q4CanonicalLabel&&q4BrowsedLabel&&q4Marker.textContent.includes(app.t('journey.current-context'))&&q4Marker.textContent.includes(q4CanonicalLabel)&&q4Marker.textContent.includes(app.t('journey.browsing-history'))&&q4Marker.textContent.includes(q4BrowsedLabel),'Q4 historical browsing does not simultaneously name canonical current and browsed historical context');
    const q4Prefix=app.navigation.fullJourney(),q4PrefixJson=JSON.stringify(q4Prefix),q4Revisit=app.terrain.visitJourneyEvent(q4TargetEvent),q4AfterRevisit=app.navigation.fullJourney();assert(q4Revisit.changed===true&&q4AfterRevisit.length===q4Prefix.length+1&&q4AfterRevisit.at(-1).actionRef==='action.journey.revisit','Q4 explicit semantic revisit did not append exactly one action.journey.revisit event');assert(JSON.stringify(q4AfterRevisit.slice(0,q4Prefix.length))===q4PrefixJson,'Q4 revisit rewrote the historical Journey prefix');for(const key of ['contextProjection','projectRef','threadRef','channelRef','selectedNodeRef'])assert((app.navigation.semanticFrame()[key]??null)===(q4TargetEvent.after[key]??null),`Q4 revisit did not restore historical semantic coordinate ${key}`);
    const q4SameFrameCount=app.navigation.fullJourney().length,q4SameFrame=app.terrain.visitJourneyEvent(q4TargetEvent);assert(q4SameFrame.changed===false&&q4SameFrame.reason==='ALREADY_CURRENT_SEMANTIC_FRAME'&&app.navigation.fullJourney().length===q4SameFrameCount,'Q4 already-current revisit manufactured semantic history');
    const q4Scrub=document.querySelector('#terrainJourneyScrub');assert(q4Scrub?.tagName==='INPUT'&&q4Scrub.type==='range'&&q4Scrub.dataset.nodeRef==='element.terrain.journey-scrub','Q4 scrub is not a native keyboard-addressable stable control');
    await app.terrain.up();const q4Language=document.querySelector('#languageSelect'),q4OriginalLanguage=q4Language.value;for(const lang of ['en','ja','zh']){q4Language.value=lang;q4Language.dispatchEvent(new Event('change',{bubbles:true}));app.terrain.render(false);for(const selector of ['[data-i18n="journey.full-history"]','[data-i18n="journey.revisit"]','[data-i18n="journey.transition-reason"]']){const value=document.querySelector(selector)?.textContent?.trim();assert(value&&!value.startsWith('journey.'),`Q4 ${lang} localization fell back for ${selector}`)}}q4Language.value=q4OriginalLanguage;q4Language.dispatchEvent(new Event('change',{bubbles:true}));app.terrain.render(false);app.terrain.closeJourney();
    checks.push('Q4 scrub stays projection-only, clusters and actionRef reason are derived, historicalFramePatch revisit is append-only, same-frame revisit is a no-op, stable native controls localize in EN/JA/ZH');

    const realMatchMedia=globalThis.matchMedia;
    globalThis.matchMedia=(query)=>query.includes('prefers-reduced-motion')?{matches:true,media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return true}}:realMatchMedia(query);
    app.terrain.render(true);
    assert(document.querySelector('#terrainFocus').style.transition==='none' && [...document.querySelectorAll('.e27-node')].every((node)=>node.style.transition==='none'), 'P07 reduced-motion projection still depends on geometry animation');
    const reducedSnapshot=app.terrain.geometrySnapshot(); assert(reducedSnapshot.current.role==='CURRENT_CONTEXT' && reducedSnapshot.nodes.length===rootChildren.length, 'P07 reduced-motion state lost comprehensible geometry');
    const reducedChild=app.terrain.childRefs()[0]||null,reducedSequence=app.terrain.transitionSnapshot().sequence;
    if(reducedChild){await app.terrain.travel(reducedChild,'in');const reducedTransition=app.terrain.transitionSnapshot();assert(reducedTransition.phase==='IDLE'&&reducedTransition.reduced===true&&reducedTransition.sequence===reducedSequence+1,'P07 reduced-motion travel did not preserve immediate semantic transition truth');await app.terrain.up();}
    globalThis.matchMedia=realMatchMedia; app.terrain.render(false);
    checks.push('P07 reduced-motion removes adaptive geometry animation without removing spatial meaning or semantic travel');

    const mobileFrame=document.createElement('iframe'); mobileFrame.style.cssText='position:fixed;left:-10000px;top:0;width:390px;height:844px;border:0'; const mobileUrl=new URL(location.href); mobileUrl.searchParams.delete('integration'); mobileFrame.src=mobileUrl.href; await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('P15 mobile frame timed out')),5000);mobileFrame.onload=()=>{clearTimeout(timeout);resolve()};document.body.append(mobileFrame)}); for(let mobileReadyAttempt=0;mobileReadyAttempt<150&&!mobileFrame.contentWindow?.__VEXLIFE_APP__;mobileReadyAttempt++)await delay(20);assert(Boolean(mobileFrame.contentWindow?.__VEXLIFE_APP__),'P15 mobile app binding did not become ready after load');
    const mobileWindow=mobileFrame.contentWindow,mobileDocument=mobileFrame.contentDocument,mobileTerrain=mobileDocument.querySelector('#view-terrain'),mobileFocus=mobileDocument.querySelector('#terrainFocus'),mobileVex=mobileDocument.querySelector('#guideWindow');
    assert(mobileWindow.innerWidth<=390 && mobileDocument.documentElement.scrollWidth<=mobileWindow.innerWidth+1, 'P15 mobile first render introduces horizontal document overflow');
    assert(mobileFocus?.dataset.adaptiveGeometry==='CURRENT_CONTEXT' && mobileDocument.querySelectorAll('.e27-node').length===rootChildren.length, 'P15 mobile first render lost accepted Terrain context/topology');
    assert(mobileVex?.classList.contains('is-minimized'), 'P15 mobile first-render Vex no longer starts ambient/minimized');
    const mobileJourneyToggle=mobileDocument.querySelector('[data-node-ref="element.terrain.journey-full-history"]');assert(mobileJourneyToggle,'Q4 mobile journey trigger stable identity is missing');const mobileJourneyToggleRect=mobileJourneyToggle.getBoundingClientRect(),mobileJourneyToggleStyle=mobileWindow.getComputedStyle(mobileJourneyToggle);assert(mobileJourneyToggleStyle.display!=='none'&&mobileJourneyToggleStyle.visibility!=='hidden'&&mobileJourneyToggleRect.width>0&&mobileJourneyToggleRect.height>0,'Q4 mobile journey trigger is not visibly reachable');mobileJourneyToggle.click();await delay(40);const mobileJourneyDrawer=mobileDocument.querySelector('#terrainJourneyDrawer'),mobileJourneyScrub=mobileDocument.querySelector('[data-node-ref="element.terrain.journey-scrub"]');assert(mobileJourneyDrawer?.classList.contains('show')&&mobileJourneyScrub?.type==='range'&&mobileDocument.documentElement.scrollWidth<=mobileWindow.innerWidth+1,'Q4 mobile semantic Journey affordance is unusable or introduces horizontal overflow');
    const mobileTerrainRect=mobileTerrain.getBoundingClientRect(),mobileFocusRect=mobileFocus.getBoundingClientRect(); assert(mobileFocusRect.right>mobileTerrainRect.left && mobileFocusRect.left<mobileTerrainRect.right && mobileFocusRect.bottom>mobileTerrainRect.top && mobileFocusRect.top<mobileTerrainRect.bottom, 'P15 current context is not visible in mobile Terrain viewport');
    const mobileEvidence={viewport:{width:mobileWindow.innerWidth,height:mobileWindow.innerHeight},documentScrollWidth:mobileDocument.documentElement.scrollWidth,currentRole:mobileFocus.dataset.adaptiveGeometry,nodeCount:mobileDocument.querySelectorAll('.e27-node').length,vexAmbient:mobileVex.classList.contains('is-minimized')}; mobileFrame.remove();
    checks.push('P15 accepted E2.7 mobile first-render Terrain usability remains present at a real 390px Chromium browsing context');

    state.e28Poc01={schemaVersion:'vexlife.e28-poc01.browser-proof/v1',semanticContextRef:rootRef,canonical,projectionProofs,offset:offsetGeometry,pinned,recovered:resetGeometry,reducedMotion:reducedSnapshot,mobile:mobileEvidence};
    assert(app.terrain.currentRef()===rootRef, 'Terrain suite did not restore canonical root baseline');
    return { suiteRef:this.suiteRef, state:'PASS', baselineRef:'baseline.vexlife.browser.root-terrain', checks };
  }
});

// [VXG RealForever]
